# 投递要求
require:
  expectedCount: 0  # 期望岗位(BOSS 上推荐旁边的选项，自己创建的求职期望) 默认0为推荐
  cityCode: "北京"
  jobType: "全职"
  salary: "20-50K" # 薪资（单选）："3K以下", "3-5K", "5-10K", "10-20K", "20-50K", "50K以上"                         列表筛选
  minimumWage: 17 # 薪资区间最小值判定 比如6-23可能在区间内但是基本给不到 (6 >= minimumWage )          可以不指定      投递前验证
  maxWage: 26 # 用于最低值的最大判定 比如离谱的区间 100-1000k (maxWage >= 100)  可以不指定
  expectWage: 20 # 你的期望薪资 在区间内就会投递（会受到上面的二次判定） 可以不指定 
  experiences: [ "5-10年" ] # 工作经验："应届毕业生", "1年以下", "1-3年", "3-5年", "5-10年", "10年以上"               列表筛选
  educations: [ "本科" ] # 学历: "初中及以下", "中专/中技", "高中", "大专", "本科", "硕士", "博士"                     列表筛选
  industries: [] # 公司行业                                                                                       投递前验证
  scales: [ "100-499人" ] # 规模 "0-20人", "20-99人", "100-499人", "500-999人", "1000-9999人", "10000人以上"        列表筛选
  financings: [ "不限" ] # 融资阶段 "未融资", "天使轮", "A轮", "B轮", "C轮", "D轮及以上", "已上市", "不需要融资"        投递前验证    
  activeTimeDesc: [ "刚刚活跃","今日活跃" ] # 活跃时间要求                                                            投递前验证    
  keyword: "" # 搜索关键词 可不填                                                                                       列表筛选
  companyBlacklist: [  ] # 公司黑名单                                                                                投递前验证    
  jobNameExclusions: [ "经理", "运维","组长", "游戏", "测试"] # 岗位名称关键词排除 只要包含就不会投递 慎重选择                           投递前验证    
  keywordExclusions: [ "游戏" ] # 描述关键词排除 只要包含就不会投递 慎重选择                                    投递前验证    
  recruiterExclusions: [ "猎头", "CTO"] # 招聘人员排除                                                                 投递前验证    
  

